make lcov work

diff --git a/.github/workflows/lcov.yml b/.github/workflows/lcov.yml
--- a/.github/workflows/lcov.yml
+++ b/.github/workflows/lcov.yml
@@ -15,4 +15,12 @@ jobs:
         working-directory: api
         run: |
           cargo llvm-cov --all-features --json --output-path lcov.json
-          cat lcov.json | jq '.data[0].totals.lines.percent'
+          coverage=`cat lcov.json | jq '.data[0].totals.lines.percent'`
+          result=`echo "$coverage>95" | bc
+          if [[ $result == 1 ]]; then
+            echo "coverage test passed with $coverage% coverage"
+            exit 0
+          else
+            echo "coverage test failed with $coverage% coverage (95% required)"
+            exit 1
+          fi
